package main

import (
	"myapp/mylib/algorithm"
	"myapp/mylib/exam"
)

func main() {
	//myexcel.MyExcel()
	//mypool.MyPool()
	//algorithm.SpliterArray()
	//algorithm.FirstMissingPositive()
	//base.MyGoroutine()
	//	base.MyTrace1()
	//algorithm.JieYuShui()
	//algorithm.MyWordBreak()
	//base.Concurrence()
	//base.MyJson()
	//mysort.HeapSort()
	//mysort.MyShell()
	//mysort.MyInsert()
	//a := []int{}
	//fmt.Println(cap(a))
	//algorithm.MyKmp()
	//algorithm.UniquePathsWithObstacles()
	//base.MyArray()
	//	algorithm.ArrayToForest()
	//	algorithm.HasPathSum()
	//base.MySlice()
	//	base.MyInterface()
	//algorithm.MyIsValidBST()
	//algorithm.DelNodes()
	//algorithm.ShiftGrid()
	//algorithm.NumTrees()
	//algorithm.Largest1BorderedSquare()
	//a := 4
	//b := -4
	//fmt.Println(a & b)
	//algorithm.Triangle()
	//algorithm.Distence()
	//exam.TestWaitGroup()
	//algorithm.Bag01()
	algorithm.PseudoEncrypt()
	//algorithm.HasPathSum()
	//base.MySlice()
	//base.MyPointer()
	//algorithm.MyFindPeakElement()
	//algorithm.HeightChecker()
	//	algorithm.CanMakePaliQueries()
	//algorithm.IsSubPath()
	//	link.HuiWen()
	//link.ReverseList()
	//link.HasCycle()
	//link.MergeTwoLists()
	//link.RemoveNthFromEnd()
	//link.MiddleNode()
	//mysort.MyInsert()
	//mysort.MergeSort()
	///mysort.QuickSort()
	//search.Bsearch()
	//link.GetIntersectionNode()
	//tree.MaxDepth()
	//test.MyReverse()
	//hash.ShiWanUrl()
	//algorithm.MinimumTotal()
	//mystring.BF()
	//mystring.KMP()
	//divide.ReverseCount()
	exam.TwoSum()
}
